//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wnmp.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wnmp.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow remote root access.
        /// </summary>
        public static string ALLOW_REMOTE_ROOT_ACCESS {
            get {
                return ResourceManager.GetString("ALLOW_REMOTE_ROOT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already running.
        /// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string APPLICATION {
            get {
                return ResourceManager.GetString("APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string APPLICATIONS {
            get {
                return ResourceManager.GetString("APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string AUTOMATICALLY_CHECK_FOR_UPDATES {
            get {
                return ResourceManager.GetString("AUTOMATICALLY_CHECK_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backed up.
        /// </summary>
        public static string BACKED_UP {
            get {
                return ResourceManager.GetString("BACKED_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CHECK_FOR_UPDATES {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Support.
        /// </summary>
        public static string COMMUNITY_SUPPORT {
            get {
                return ResourceManager.GetString("COMMUNITY_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string CONFIGURATION {
            get {
                return ResourceManager.GetString("CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2012 - {CURRENTYEAR} by Kurt Cancemi.
        /// </summary>
        public static string COPYRIGHT_TEXT {
            get {
                return ResourceManager.GetString("COPYRIGHT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read update information.
        /// </summary>
        public static string COULDNT_READ_UPDATE_INFORMATION {
            get {
                return ResourceManager.GetString("COULDNT_READ_UPDATE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DONATE {
            get {
                return ResourceManager.GetString("DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress, please wait....
        /// </summary>
        public static string DOWNLOAD_IN_PROGRESS_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("DOWNLOAD_IN_PROGRESS_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update....
        /// </summary>
        public static string DOWNLOADING_UPDATE {
            get {
                return ResourceManager.GetString("DOWNLOADING_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string EDITOR {
            get {
                return ResourceManager.GetString("EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string FILE_MENU {
            get {
                return ResourceManager.GetString("FILE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated SSL Keypair.
        /// </summary>
        public static string GENERATED_SSL_KEYPAIR {
            get {
                return ResourceManager.GetString("GENERATED_SSL_KEYPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Headers.
        /// </summary>
        public static string GET_HEADERS {
            get {
                return ResourceManager.GetString("GET_HEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get HTTP Headers.
        /// </summary>
        public static string GET_HTTP_HEADERS {
            get {
                return ResourceManager.GetString("GET_HTTP_HEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string HELP_MENU {
            get {
                return ResourceManager.GetString("HELP_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string HOST_SC {
            get {
                return ResourceManager.GetString("HOST_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host To IP.
        /// </summary>
        public static string HOST_TO_IP {
            get {
                return ResourceManager.GetString("HOST_TO_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Control Panel.
        /// </summary>
        public static string INITIALIZING_CONTROL_PANEL {
            get {
                return ResourceManager.GetString("INITIALIZING_CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password Format.
        /// </summary>
        public static string INVALID_PASSWORD_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP(s).
        /// </summary>
        public static string IP_S {
            get {
                return ResourceManager.GetString("IP_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        public static string LATEST_VERSION_SC {
            get {
                return ResourceManager.GetString("LATEST_VERSION_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LOGS {
            get {
                return ResourceManager.GetString("LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MariaDB data directory &apos;{dataDirectory}&apos; already exists, to continue with the setup it will be deleted. Is that OK? Please backup any data that you don&apos;t want lost in that directory before proceeding..
        /// </summary>
        public static string MARIADB_DATA_DIR_EXISTS {
            get {
                return ResourceManager.GetString("MARIADB_DATA_DIR_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MariaDB Setup.
        /// </summary>
        public static string MARIADB_SETUP {
            get {
                return ResourceManager.GetString("MARIADB_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MariaDB Version:.
        /// </summary>
        public static string MARIADB_VERSION {
            get {
                return ResourceManager.GetString("MARIADB_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string MINIMIZE_TO_TRAY {
            get {
                return ResourceManager.GetString("MINIMIZE_TO_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray instead of closing.
        /// </summary>
        public static string MINIMIZE_TO_TRAY_INSTEAD_OF_CLOSING {
            get {
                return ResourceManager.GetString("MINIMIZE_TO_TRAY_INSTEAD_OF_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        public static string MOVED {
            get {
                return ResourceManager.GetString("MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found!.
        /// </summary>
        public static string NEW_VERSION_FOUND_EX {
            get {
                return ResourceManager.GetString("NEW_VERSION_FOUND_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nginx Version:.
        /// </summary>
        public static string NGINX_VERSION {
            get {
                return ResourceManager.GetString("NGINX_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running.
        /// </summary>
        public static string NOT_RUNNING {
            get {
                return ResourceManager.GetString("NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MariaDB Shell.
        /// </summary>
        public static string OPEN_MARIADB_SHELL {
            get {
                return ResourceManager.GetString("OPEN_MARIADB_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not be blank or contain spaces..
        /// </summary>
        public static string PASSWORD_CREATE_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_CREATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        public static string PHP_EXTENSIONS {
            get {
                return ResourceManager.GetString("PHP_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Port:.
        /// </summary>
        public static string PHP_PORT {
            get {
                return ResourceManager.GetString("PHP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Processes:.
        /// </summary>
        public static string PHP_PROCESSES {
            get {
                return ResourceManager.GetString("PHP_PROCESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Version:.
        /// </summary>
        public static string PHP_VERSION {
            get {
                return ResourceManager.GetString("PHP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string REPORT_BUG {
            get {
                return ResourceManager.GetString("REPORT_BUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarted.
        /// </summary>
        public static string RESTARTED {
            get {
                return ResourceManager.GetString("RESTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Password:.
        /// </summary>
        public static string ROOT_PASSWORD {
            get {
                return ResourceManager.GetString("ROOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text editor.
        /// </summary>
        public static string SELECT_A_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("SELECT_A_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup MariaDB.
        /// </summary>
        public static string SETUP_MARIADB {
            get {
                return ResourceManager.GetString("SETUP_MARIADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        public static string START_ALL {
            get {
                return ResourceManager.GetString("START_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start MariaDB on launch.
        /// </summary>
        public static string START_MARIADB_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_MARIADB_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Nginx on launch.
        /// </summary>
        public static string START_NGINX_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_NGINX_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PHP on launch.
        /// </summary>
        public static string START_PHP_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_PHP_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Wnmp minimized.
        /// </summary>
        public static string START_WNMP_MINIMIZED {
            get {
                return ResourceManager.GetString("START_WNMP_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Wnmp with Windows.
        /// </summary>
        public static string START_WNMP_WITH_WINDOWS {
            get {
                return ResourceManager.GetString("START_WNMP_WITH_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string STARTED {
            get {
                return ResourceManager.GetString("STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started MariaDB shell.
        /// </summary>
        public static string STARTED_MARIADB_SHELL {
            get {
                return ResourceManager.GetString("STARTED_MARIADB_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All.
        /// </summary>
        public static string STOP_ALL {
            get {
                return ResourceManager.GetString("STOP_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string STOPPED {
            get {
                return ResourceManager.GetString("STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string TOOLS_MENU {
            get {
                return ResourceManager.GetString("TOOLS_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check interval (in days).
        /// </summary>
        public static string UPDATE_CHECK_INTERVAL_IN_DAYS {
            get {
                return ResourceManager.GetString("UPDATE_CHECK_INTERVAL_IN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changelog.
        /// </summary>
        public static string VIEW_CHANGELOG {
            get {
                return ResourceManager.GetString("VIEW_CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string VISIBLE {
            get {
                return ResourceManager.GetString("VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnmp Control Panel.
        /// </summary>
        public static string WNMP_CONTROL_PANEL {
            get {
                return ResourceManager.GetString("WNMP_CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnmp is an easy Nginx, MariaDB, and PHP environment for Windows..
        /// </summary>
        public static string WNMP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WNMP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnmp Directory.
        /// </summary>
        public static string WNMP_DIRECTORY {
            get {
                return ResourceManager.GetString("WNMP_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnmp Options.
        /// </summary>
        public static string WNMP_OPTIONS {
            get {
                return ResourceManager.GetString("WNMP_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnmp Version: {CURRENTVERSION}.
        /// </summary>
        public static string WNMP_VERSION {
            get {
                return ResourceManager.GetString("WNMP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download this update?.
        /// </summary>
        public static string WOULD_YOU_LIKE_TO_DOWNLOAD_THIS_UPDATE_QM {
            get {
                return ResourceManager.GetString("WOULD_YOU_LIKE_TO_DOWNLOAD_THIS_UPDATE_QM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version:.
        /// </summary>
        public static string YOUR_VERSION_SC {
            get {
                return ResourceManager.GetString("YOUR_VERSION_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version {CURRENTVERSION} is up to date..
        /// </summary>
        public static string YOUR_VERSION_VER_IS_UP_TO_DATE_DOT {
            get {
                return ResourceManager.GetString("YOUR_VERSION_VER_IS_UP_TO_DATE_DOT", resourceCulture);
            }
        }
    }
}
